name: gameHub-system

services:
  postgres-gamehub:
    image: postgres:17.8
    environment:
      POSTGRES_USER: ${GAMEHUB_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${GAMEHUB_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${GAMEHUB_DATASOURCE_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./data-source:/var/lib/postgresql/data
    restart: always
    networks:
      - gameHub-network

  gamehub-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres-gamehub
    environment:
      -
    restart: on-failure
    networks:
      - gameHub-network

networks:
  gameHub-network:
    driver: bridge