services:
  springboot-app:
    container_name: game-hub
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    env_file:
      - .env
    environment:
      GAME_HUB_DATASOURCE_URL: ${GAME_HUB_DATASOURCE_URL_DOCKER}
    ports:
      - "8080:8080"
    restart: on-failure

  
  postgresql:
    image: postgres:16.9-bullseye
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${GAME_HUB_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${GAME_HUB_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${GAME_HUB_DATASOURCE_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
