spring.application.name=gamehub
server.port=8080
spring.config.import=optional:file:.env[.properties]

spring.r2dbc.username=${GAMEHUB_DATASOURCE_USERNAME}
spring.r2dbc.password=${GAMEHUB_DATASOURCE_PASSWORD}
spring.r2dbc.url=${GAMEHUB_DATASOURCE_URL}
